
branding:
  icon: 'anchor'
  color: 'green'
name: "Setup dockerode"
description: setup Docker and Nodejs environment, e.g. as a foundation of github.com/apocas/dockerode.
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@main
      with:
        check-latest: true
        node-version: lts/*
    - uses: ScribeMD/rootless-docker@main
      name: Use Docker in rootless mode.
    - uses: actions/checkout@main
    
    
