branding:
  icon: "anchor"
  color: "green"
name: "Setup dockerode"
description: setup Docker and Nodejs environment, e.g. as a foundation of github.com/apocas/dockerode.
inputs:
  action-provider:
    description: "Github Action provider"
    required: false
    default: "davidkhala"
  password:
    description: "Password for Docker Hub"
    required: false
    default: "dckr_pat_ua37yOmE1Xqy2kUOIZEqul2P5Sc"
  username:
    description: "Username for Docker Hub"
    required: false
    default: "davidkhala"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@main
      with:
        check-latest: true
        node-version: lts/*
    - if: runner.os == 'Linux' && inputs.action-provider == 'docker'
      uses: docker/setup-docker-action@master
      with:
        rootless: true
        set-host: true
        context: rootless
    - if: runner.os == 'Linux' && inputs.action-provider == 'davidkhala'
      uses: davidkhala/rootless-docker@main
    - if: runner.os == 'macOS'
      uses: douglascamata/setup-docker-macos-action@main
    - uses: docker/login-action@master
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - uses: actions/checkout@main
