branding:
  icon: "anchor"
  color: "green"
name: "Setup dockerode"
description: setup Docker and Nodejs environment, e.g. as a foundation of github.com/apocas/dockerode.
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@main
      with:
        check-latest: true
        node-version: lts/*
    - if: runner.os == 'Linux'
      uses: docker/setup-docker-action@master
      with:
        rootless: true
    - if: runner.os == 'macOS'
      uses: douglascamata/setup-docker-macos-action@main
    - uses: actions/checkout@main
