name: self test

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: docker context list
      - run: docker context inspect default
